### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by MatheusRV** [ElanUtta/Site-php#1]
@ElanUtta E aiii bem vindo ao GitHub... Parabéns por esse repositório depois inclui um readme para ele ficar ainda mais bonito.

Se ainda estiver um pouco perdido pelo GitHub acesse: https://services.github.com/on-demand/intro-to-github/ e realize o treinamento básico.

https://help.github.com/articles/about-readmes/

Olha esse modelo: https://github.com/dbader/readme-template/tree/master/portuguese

**Comment by ElanUtta** [comment]
Vlw Man, vou dar uma olhada. Eu acabei me esquecendo de por ele. Tive problemas na hora de dar o push/pull. Pq já tenho uma conta no gitlab. Ae tá dando meio que interferência entre as contas saca. Não consigo reconfigurar.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
